export const categoryList = [
  {
    id: 1,
    value: "place",
    label: "350 kW",
  },
  {
    id: 2,
    value: "dish",
    label: "550 kW",
  },
];

export const dataList = [
  {
    id: 1,
    title: "Portable Emergency Backup Generators",
    serviceTime: "45-60min",
    deliveryFee: 3.44,
    category: "place",
    cuisine: "portable generators",
    rating: 5,
    price: 2500,
    coverSrc:
      "https://www.electricgeneratorsdirect.com/img-assets/hybrid_page_21399.jpg",
  },
  {
    id: 2,
    title: "Kohler 20RESCL-200SELS",
    serviceTime: "15-20min",
    deliveryFee: 4.94,
    category: "place",
    cuisine: "standby generators",
    rating: 4,
    price: 1000,
    coverSrc:
      "https://www.electricgeneratorsdirect.com/products-image/150/20RESAL-SA6_11406_600.jpg",
  },
  {
    id: 3,
    title: "DuroMax XP5500EH Electric Start-Camping & RV Ready",
    serviceTime: "30-22min",
    deliveryFee: 4.94,
    category: "place",
    cuisine: "gasoline generators",
    rating: 3,
    price: 2000,
    coverSrc: "https://m.media-amazon.com/images/I/815UIExw6VS._AC_UY218_.jpg",
  },
  {
    id: 4,
    title: "Portable Quiet Inverter Generators",
    serviceTime: "10-18min",
    deliveryFee: 2.14,
    category: "place",
    cuisine: "portable generators",
    rating: 1,
    price: 1800,
    coverSrc:
      "https://www.electricgeneratorsdirect.com/img-assets/hybrid_page_21402.jpg",
  },
  {
    id: 5,
    title: "Generac PowerPact",
    serviceTime: "25-30min",
    deliveryFee: 6.79,
    category: "place",
    cuisine: "standby generators",
    rating: 5,
    price: 2000,
    coverSrc:
      "https://www.electricgeneratorsdirect.com/products-image/150/6998_70157_600.jpg",
  },
  {
    id: 6,
    title: "Westinghouse Outdoor Power Equipment WGen5300v Portable Generator",
    serviceTime: "5-15min",
    deliveryFee: 2.87,
    category: "place",
    cuisine: "gasoline generators",
    rating: 5,
    price: 3500,
    coverSrc: "https://m.media-amazon.com/images/I/810EChJ85RL._AC_UY218_.jpg",
  },
  {
    id: 7,
    title: "Portable Recreational Generators",
    serviceTime: "50-65min",
    deliveryFee: 8.5,
    category: "dish",
    cuisine: "portable generators",
    rating: 2,
    price: 2200,
    coverSrc:
      "https://www.electricgeneratorsdirect.com/img-assets/hybrid_page_21400.jpg",
  },
  {
    id: 8,
    title: "Generac Guardian",
    serviceTime: "10-15min",
    deliveryFee: 1.8,
    category: "dish",
    cuisine: "standby generators",
    rating: 1,
    price: 1900,
    coverSrc:
      "https://www.electricgeneratorsdirect.com/products-image/150/7043_70169_600.jpg",
  },
  {
    id: 9,
    title: "WEN 56475 4750-Watt Portable Generator",
    serviceTime: "12-18min",
    deliveryFee: 3.33,
    category: "dish",
    cuisine: "gasoline generators",
    rating: 4,
    price: 2750,
    coverSrc: "https://m.media-amazon.com/images/I/81Z+EapiOCL._AC_UY218_.jpg",
  },
  {
    id: 10,
    title: "Portable Professional Generators",
    serviceTime: "30-38min",
    deliveryFee: 1.9,
    category: "dish",
    cuisine: "portable generators",
    rating: 2,
    price: 4350,
    coverSrc:
      "https://www.electricgeneratorsdirect.com/img-assets/hybrid_page_21401.jpg",
  },
  {
    id: 11,
    title: "Kohler 10RESVL",
    serviceTime: "16-20min",
    deliveryFee: 4.1,
    category: "dish",
    cuisine: "standby generators",
    rating: 3,
    price: 3300,
    coverSrc:
      "https://www.electricgeneratorsdirect.com/products-image/150/egd-10resvl-100lc12-kit-a_121097_1000_88fcb03cb16fb5eb7128c79d658a7b84.jpg",
  },
  {
    id: 12,
    title: "Westinghouse Outdoor Power Equipment",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "dish",
    cuisine: "gasoline generators",
    rating: 2,
    price: 4100,
    coverSrc: "https://m.media-amazon.com/images/I/81WO1jafMpL._AC_UY218_.jpg",
  },
];
